name: Workflow to push to ACR

on:
  push:
    branches: ["main"]

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: node version
        run: node --version

      - name: Docker version
        run: docker --version

  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and build docker image
        run: git clone https://github.com/${{ github.repository }} .

      - name: Build Docker Image
        run: docker build -t travel-list .

      - name: Docker image show
        run: docker images

      - name: Dockerhub login
        run: docker login myacr102002.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Tag Docker Image
        run: docker tag travel-list myacr102002.azurecr.io/travel-list:${{ github.sha }}

      - name: Push Docker Image
        run: docker push myacr102002.azurecr.io/travel-list:${{ github.sha }}
