name: Workflow to push to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: deploy image to vm
        run: |
          ssh -i ${{ secrets.PRIVATE_KEY }} utkarsh@${{ secrets.IP_ADDRESS }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/travel-list:${{ github.sha }}
          docker stop travel-list || true
          docker rm travel-list || true
          docker run -d -p 3000:3000 --name travel-list ${{ secrets.DOCKER_USERNAME }}/travel-list:${{ github.sha }}
