name: Workflow to push to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: node version
        run: node --version

      - name: Docker version
        run: docker --version

  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and build docker image
        run: git clone https://github.com/${{ github.repository }} .

      - name: Build Docker Image
        run: docker build -t travel-list .

  show-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker image show
        run: docker images

  login-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Docker image show
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Docker Image
        run: docker tag travel-list ${{ secrets.DOCKER_USERNAME }}/travel-list:${{ github.sha }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/travel-list:${{ github.sha }}
