name: Workflow to push to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: git clone https://github.com/${{ github.repository }} .

      - name: node version
        run: node --version

      - name: contents of current directory
        run: ls -a

      - name: Docker version
        run: docker --version

      - name: Build Docker Image
        run: docker build -t travel-list .

      - name: Docker image show
        run: docker images
